-- Arogya Cafe — initial schema. Targets PostgreSQL (runtime) and H2 in PostgreSQL mode (tests).
-- Instant fields are TIMESTAMP WITH TIME ZONE to match Hibernate's UTC instant mapping.

-- ---- Reference / catalog ----
CREATE TABLE category (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE ingredient (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL UNIQUE,
    unit       VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE menu_item (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    size_variant VARCHAR(255) NOT NULL,
    price        NUMERIC(10, 2) NOT NULL,
    category_id  BIGINT NOT NULL REFERENCES category (id),
    created_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE item_ingredient (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_item_id  BIGINT NOT NULL REFERENCES menu_item (id),
    ingredient_id BIGINT NOT NULL REFERENCES ingredient (id),
    quantity      NUMERIC(12, 3) NOT NULL,
    unit          VARCHAR(255) NOT NULL,
    size_variant  VARCHAR(255),
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

-- ---- Inventory ----
CREATE TABLE supplier (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    contact    VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE inventory_stock (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_id     BIGINT NOT NULL UNIQUE REFERENCES ingredient (id),
    qty_on_hand       NUMERIC(14, 3) NOT NULL,
    reorder_threshold NUMERIC(14, 3) NOT NULL,
    last_updated      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE stock_transaction (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_stock_id BIGINT NOT NULL REFERENCES inventory_stock (id),
    type               VARCHAR(20) NOT NULL,
    quantity           NUMERIC(14, 3) NOT NULL,
    triggered_by       VARCHAR(255) NOT NULL,
    supplier_id        BIGINT REFERENCES supplier (id),
    order_id           BIGINT,
    created_at         TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at         TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

-- ---- People ----
CREATE TABLE customer (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    contact    VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE staff (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    role          VARCHAR(20) NOT NULL,
    username      VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

-- ---- Order workflow ----
CREATE TABLE orders (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customer (id),
    status      VARCHAR(20) NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE order_line (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT NOT NULL REFERENCES orders (id),
    menu_item_id BIGINT NOT NULL REFERENCES menu_item (id),
    size_variant VARCHAR(255) NOT NULL,
    quantity     INTEGER NOT NULL,
    unit_price   NUMERIC(10, 2) NOT NULL,
    created_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE kot (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT NOT NULL UNIQUE REFERENCES orders (id),
    status     VARCHAR(20) NOT NULL,
    issued_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE bill (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       BIGINT NOT NULL UNIQUE REFERENCES orders (id),
    total_amount   NUMERIC(12, 2) NOT NULL,
    payment_status VARCHAR(20) NOT NULL,
    billed_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

-- ---- Many-to-many join tables (Staff handles Orders, fulfils KOTs) ----
CREATE TABLE order_staff (
    order_id BIGINT NOT NULL REFERENCES orders (id),
    staff_id BIGINT NOT NULL REFERENCES staff (id),
    PRIMARY KEY (order_id, staff_id)
);

CREATE TABLE kot_staff (
    kot_id   BIGINT NOT NULL REFERENCES kot (id),
    staff_id BIGINT NOT NULL REFERENCES staff (id),
    PRIMARY KEY (kot_id, staff_id)
);

-- Helpful indexes for FK lookups used by the workflow.
CREATE INDEX idx_menu_item_category ON menu_item (category_id);
CREATE INDEX idx_item_ingredient_menu_item ON item_ingredient (menu_item_id);
CREATE INDEX idx_order_line_order ON order_line (order_id);
CREATE INDEX idx_stock_txn_stock ON stock_transaction (inventory_stock_id);
CREATE INDEX idx_stock_txn_order ON stock_transaction (order_id);
